---
- name: create users using a loop
  hosts: all
  tasks:
   - name: create users
     user:
      name: "{{ item.name }}"
      state: present
      groups: "{{ item.groups }}"
     loop:
      - name: kiran
        group: wheel
      - name: nani
        group: users
      - name: suresh
        group: users
