---
- name: test register
  hosts: all
  tasks:
   - shell: cat/etc/passwd  #it is used to create variable
     register: passwd_contents  # VARIABLE IS STORED IN PASSED_CONTENTS
   - debug:
      msg: echo "passwd contains user lisa" #display the variable value
     when: passwd_contents.stdout.find('lisa') != -1 
