---
- name: using multiple conditions
  hosts: all
  tasks:
    - packages:
       name: httpd
       state: installed
      when:
       - ansible_distribution == "RedHat"
       - ansible_memfree_mb > 1512  
